### ISSUE TITLE
Videos cannot be uploaded

### ISSUE THREAD

**Issue by hale6666** [liam-middlebrook/gallery#28] opened 2017-10-13 15:34 UTC
Videos cannot be uploaded, even if smaller than the max size.  If you click in the dropzone, then select a video, it does not show up in the list of files to upload, nor will it upload if "Upload" is pressed.  The video tested is of a supported type (MP4).  Photos are unaffected.

**Comment by liam-middlebrook** [comment] 2017-10-21 02:43
Duplicate of #27

**Closed by liam-middlebrook** 2017-10-21 02:43 UTC
Labels: duplicate
